# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Creates a zip file out of each of the directories in this repo (excluding directories that start with a dot)
      - name: Create zip files
        run: |
          for dir in $(ls -d */ | grep -v '^\..*'); do
            zip -r ${dir%/}.zip $dir
          done

      # copies the created zip files to the server under /world/datapacks
      - name: Copy zip files to server
        run: |
          for file in $(ls *.zip); do
            curl -T $file -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/world/datapacks/$file
          done

      # make a rcon connection to the server (with password) and execute /reload (minecraft server command)
      - name: Reload server
        run: |
          echo "/reload" | nc -q 1 -u ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_PORT }} -p ${{ secrets.SERVER_PASSWORD }}
